from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


class SqlAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages procesed by the SQL agent.")
    user_question:str = Field(..., description="The question asked by the user.")
    curated_ques:str = Field(..., description="Curated user question")
    prompt_query_context:str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query.")
    generated_sql_query:str = Field(..., description="The SQL query generated by the agent based on the user's question and the provided context.")
    is_safe: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute. 'Yes' means it's safe, 'No' means it's not.")
    comments:str = Field(..., description="Comment regarding the safety of the SQL query.")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The final answer generated by the agent based on the SQL query execution result and the curated question")
    db_connection_string: str = Field(default="", description="The specific DB connection string to use")




class SqlJudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the SQL query is safe to execute. 'Yes' means it's safe, 'No' means it's not.")
    comments:str = Field(..., description="Comment regarding the safety of the SQL query.")


class ETLAgentSchema(BaseModel):
    messages:Annotated[list, add] = Field(..., description="List of messages processed by the ETL agent.")
    user_input: str = Field(default="", description="The user's ETL request")
    python_code: str = Field(default="", description="The generated Python script")
    execution_result: str = Field(default="", description="Output of the script execution")
    db_connection_string: str = Field(default="", description="The specific DB connection string to use")

class DataAnalystSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages")
    user_question: str = Field(..., description="The original analytical question")
    sql_agent_query: str = Field(..., description="The precise data question formulated for the SQL agent")
    sql_execution_result: str = Field(..., description="The data returned by the SQL agent")
    statistical_analysis: str = Field(..., description="The statistical analysis of the data")
    final_answer: str = Field(..., description="The final explanation provided to the user")
    db_connection_string: str = Field(default="", description="The specific DB connection string to use")

class VisualizationSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages")
    user_question: str = Field(..., description="The user's visualization request")
    sql_agent_query: str = Field(..., description="The query for the SQL agent")
    sql_execution_result: str = Field(..., description="The raw data returned by SQL")
    chart_type: str = Field(..., description="The decided chart type")
    python_code: str = Field(..., description="The Python code to generate the chart")
    image_path: str = Field(..., description="Path to the saved chart image")
    final_explanation: str = Field(..., description="Explanation of the chart")
    db_connection_string: str = Field(default="", description="The specific DB connection string to use")

class DataQualitySchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages")
    dataset_path: str = Field(..., description="Path to the dataset (CSV)")
    target_table: str = Field(default="", description="Target database table for quality check")
    db_connection_string: str = Field(default="", description="The specific DB connection string to use")
    dataset_info: str = Field(..., description="Information about the dataset (headers, sample)")
    python_code: str = Field(..., description="Code generated to check data quality")
    execution_result: str = Field(default="", description="Result of the quality check script")
    quality_report: str = Field(..., description="Final formatted quality report")

class SupervisorSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages")
    user_input: str = Field(..., description="The user's query or command")
    selected_agent: str = Field(default="", description="The agent selected by the router")
    extracted_file_path: str = Field(default="", description="Extracted file path for data quality checks")
    extracted_table_name: str = Field(default="", description="Extracted table name for data quality checks")
    final_response: str = Field(default="", description="The final response from the sub-agent")
    db_connection_string: str = Field(default="", description="The DB connection string provided via API")

class RouteDecision(BaseModel):
    agent: Literal["etl", "sql", "data_analysis", "visualization", "data_quality"] = Field(..., description="The agent to route to")
    file_path: str = Field(default="", description="If the user mentions a CSV file to check quality or process, extract its path here.")
    table_name: str = Field(default="", description="If the user mentions a database table to check quality, extract its name here.")
